#!/usr/bin/env python3

import pytest
from pyensembl.shell import collect_all_installed_ensembl_releases

import pirlygenes.gene_ids as gi
from pirlygenes import load_all_dataframes
from pirlygenes.load_dataset import get_data

_human_genomes = sorted(
    [
        g
        for g in collect_all_installed_ensembl_releases()
        if g.species.latin_name == "homo_sapiens"
    ],
    reverse=True,
    key=lambda g: g.release,
)


def _load_ensembl_id_aliases():
    """Return {alt_haplotype_id: primary_contig_id} mapping from bundled data.

    Handles two categories of Ensembl gene IDs that don't resolve in pyensembl's
    default indexing:
    1. Alt-haplotype contigs (e.g. HLA-A on HSCHR6_MHC_DBB_CTG1 → primary HLA-A)
    2. Retired IDs with a documented successor
    """
    try:
        df = get_data("ensembl-id-aliases")
        return dict(zip(df["alt_haplotype_id"], df["primary_contig_id"]))
    except Exception:
        return {}


def _resolve_in_any_release(gene_id, aliases=None):
    """Check if gene_id (or its alias) resolves in any installed Ensembl release."""
    aliases = aliases or {}
    candidates = [gene_id]
    if gene_id in aliases:
        candidates.append(aliases[gene_id])
    for candidate in candidates:
        for genome in _human_genomes:
            try:
                gene = genome.gene_by_id(candidate)
                if gene is not None:
                    return True
            except Exception:
                pass
    return False


def _split_ids(value):
    if not isinstance(value, str):
        return []
    return [token.strip() for token in value.split(";") if token.strip()]


def _collect_ensembl_gene_ids(df):
    id_columns = [
        c for c in df.columns if ("Ensembl_Gene_ID" in c or c.endswith("_Gene_IDs"))
    ]
    result = set()
    for col in id_columns:
        for value in df[col]:
            for token in _split_ids(value):
                if token.startswith("ENSG"):
                    result.add(token)
    return result


# Ensembl retires gene IDs over time (~0.5% per release).  The test tolerates
# a small unresolvable rate per dataset since Ensembl updates are outside
# our control.  Datasets with a larger share of unresolvable IDs (e.g.
# surface-proteins includes alt-haplotype MHC/KIR genes that don't have
# primary-contig equivalents) can list per-dataset thresholds.
_MAX_UNRESOLVABLE_FRACTION = 0.02  # 2% default

_PER_DATASET_TOLERANCE = {
    # surface-proteins includes ~8 alt-haplotype-only genes (HLA-DRB3/4,
    # KIR family) that have no primary-contig equivalent plus ~16 truly
    # retired IDs with no Ensembl successor.  49/2700 ≈ 1.8% with aliases.
    "surface-proteins": 0.025,
    # The derived gene-family CSVs (generated by
    # ``scripts/generate_gene_family_sets.py``) intentionally retain
    # historic ENSG IDs across Ensembl releases 77-114, so a sample
    # quantified against an old annotation can still classify by
    # stable ID. Those historic IDs are retired in the current default
    # Ensembl release, so the resolve-in-Ensembl check naturally fails
    # on them — by design, not a curation error. The tolerances below
    # reflect the historic-ID retention rate per family. Tighten if a
    # family suddenly exceeds its bound (that points at a real
    # curation typo, not annotation drift).
    "nuclear-retained-lncrnas": 0.50,         # tiny set; MALAT1 has 3 historic IDs
    "histone-genes": 0.10,
    "immune-receptor-segments": 0.40,         # IG/TR loci churn a lot across releases
    "ribosomal-protein-genes": 0.20,
    "ribosomal-protein-pseudogenes": 0.10,
    "rrna-and-pseudogenes": 0.10,
    "small-noncoding-rnas": 0.15,
    "numt-pseudogenes": 0.10,
    "hemoglobin-genes": 0.10,
}


def test_all_gene_ids_resolve_in_ensembl():
    """
    Validate that all Ensembl gene IDs in packaged CSVs resolve via pyensembl.

    Applies the bundled alt-haplotype/retirement alias map first (e.g.
    HLA-A on alt contig → HLA-A primary).  A small per-dataset fraction of
    unresolvable IDs is tolerated (retirements, alt-haplotype-only genes).

    Checks all installed human Ensembl releases, not just the default GRCh38.
    Install BOTH a current release (e.g. 112) and release 81: the
    cancer-reference-expression aggregate pools source cohorts annotated at
    the 2015 (release-81) vintage, and ~4.6k of its ENSG IDs were retired from
    Ensembl after release 81 — so a current release alone fails at ~8.7%, while
    81 + 112 leaves only ~0.8% genuinely-dead IDs (under tolerance). CI
    (.github/workflows/tests.yml) installs both for this reason.
    """
    aliases = _load_ensembl_id_aliases()

    per_dataset_missing = {}
    per_dataset_total = {}
    for name, df in load_all_dataframes():
        stem = name.replace(".csv", "")
        # Don't self-check the aliases file
        if stem == "ensembl-id-aliases":
            continue
        dataset_ids = _collect_ensembl_gene_ids(df)
        if not dataset_ids:
            continue
        missing = sorted(
            gid
            for gid in dataset_ids
            if not _resolve_in_any_release(gid, aliases=aliases)
        )
        per_dataset_missing[stem] = missing
        per_dataset_total[stem] = len(dataset_ids)

    assert per_dataset_total, "No Ensembl gene IDs were found in packaged CSVs."

    failures = []
    for stem, missing in per_dataset_missing.items():
        total = per_dataset_total[stem]
        tolerance = _PER_DATASET_TOLERANCE.get(stem, _MAX_UNRESOLVABLE_FRACTION)
        fraction = len(missing) / total if total else 0.0
        if fraction > tolerance:
            failures.append(
                f"{stem}: {len(missing)}/{total} unresolvable ({fraction:.1%} > {tolerance:.1%}). "
                f"First few: {missing[:5]}"
            )

    assert not failures, "\n".join(failures)


# Weird/old/alternate names → the stable ENSG of the current gene, through
# the full tiered resolver (direct current symbol / curated display alias /
# bundled NCBI-synonym lowest tier). The ENSG is asserted rather than the
# returned symbol: which symbol comes back depends on which Ensembl
# releases happen to be installed (an old release may still carry the old
# spelling), whereas the gene's ENSG is stable across releases and tiers.
_WEIRD_NAME_TO_ENSG = {
    # current symbols — resolve directly
    "TP53": "ENSG00000141510",
    "EGFR": "ENSG00000146648",
    "MYC": "ENSG00000136997",
    # curated literature display names (gene_names aliases)
    "p53": "ENSG00000141510",
    "NY-ESO-1": "ENSG00000184033",
    "gp100": "ENSG00000185664",
    "PSMA": "ENSG00000086205",
    "B7-H3": "ENSG00000103855",
    "PD-L1": "ENSG00000120217",
    "TROP2": "ENSG00000184292",
    # legacy renames recovered via the bundled NCBI-synonym lowest tier
    "MMSET": "ENSG00000109685",   # → NSD2
    "HER2": "ENSG00000141736",    # → ERBB2
    "GNB2L1": "ENSG00000204628",  # → RACK1
    "KIAA1524": "ENSG00000163507",  # → CIP2A
    "ODZ1": "ENSG00000009694",    # → TENM1
    "C11orf30": "ENSG00000158636",  # → EMSY
    "PARK2": "ENSG00000185345",   # → PRKN
    "CASC5": "ENSG00000137812",   # → KNL1
}


# Resolution is pinned to a single known Ensembl release so the result is
# deterministic regardless of which other releases happen to be installed —
# and so the NCBI-synonym lowest tier genuinely fires for the legacy names
# (an older installed release would otherwise still carry the old spelling
# and short-circuit it). CI installs this release in a cached step.
_BASELINE_RELEASE = 112
_BASELINE_GENOME = next(
    (g for g in _human_genomes if g.release == _BASELINE_RELEASE), None
)


@pytest.mark.skipif(
    _BASELINE_GENOME is None,
    reason=(
        f"Ensembl release {_BASELINE_RELEASE} not installed — run "
        f"`pyensembl install --release {_BASELINE_RELEASE} --species homo_sapiens`"
    ),
)
@pytest.mark.parametrize("name,ensg", sorted(_WEIRD_NAME_TO_ENSG.items()))
def test_weird_old_names_resolve_to_expected_gene(name, ensg, monkeypatch):
    """End-to-end: gnarly historical symbols resolve to the right gene
    through the common helper, against a pinned release (112)."""
    monkeypatch.setattr(gi, "genomes", [_BASELINE_GENOME])
    gene_id, _resolved_name = gi.find_canonical_gene_id_and_name(name)
    assert gene_id is not None, f"{name} did not resolve"
    assert gene_id.split(".")[0] == ensg
