# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import csv
import gzip
from functools import lru_cache
from pathlib import Path
from typing import Optional, Sequence, Tuple, List

from tqdm import tqdm
import pyensembl
from pyensembl.shell import collect_all_installed_ensembl_releases

from .gene_names import get_alias_as_list, get_reverse_alias_as_list, short_gene_name

genomes = sorted(
    [
        g
        for g in collect_all_installed_ensembl_releases()
        if g.species.latin_name == "homo_sapiens"
    ],
    reverse=True,
    key=lambda g: g.release,
)

_installed_releases = " ".join([str(g.release) for g in genomes])

# ---------------------------------------------------------------------------
# Batch indexes — built once from the latest installed Ensembl release.
# ---------------------------------------------------------------------------

_gene_id_to_name: dict = {}
_transcript_id_to_gene_name: dict = {}
_indexes_built = False
_gene_id_miss_cache: set[str] = set()
_transcript_id_miss_cache: set[str] = set()


# ---------------------------------------------------------------------------
# Shared identifier primitives.
#
# These are the single implementations of two semantic tasks — "strip an
# Ensembl version suffix" and "resolve an Ensembl gene ID against one
# genome" — that both this module's multi-release lookups and the
# builders' single-release harmonizers (``pirlygenes.builders.gene_mapping``)
# build on. They live here, in the core identifier module, so the
# dependency runs builders → core and there is exactly one code path per
# task to test.
# ---------------------------------------------------------------------------


def strip_version(gene_id: str) -> str:
    """``ENSG00000251562.5`` → ``ENSG00000251562`` (idempotent on bare IDs)."""
    return str(gene_id).split(".", 1)[0].strip()


def gene_for_ensembl_id(genome, gene_id: str):
    """Resolve an Ensembl gene ID to a pyensembl ``Gene`` (or None).

    Version-tolerant, exception-swallowing single-release lookup — the
    one primitive every "by Ensembl ID" path goes through.
    """
    try:
        return genome.gene_by_id(strip_version(gene_id))
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Lowest-tier symbol synonyms: a bundled, static snapshot of NCBI
# gene_info ``Synonyms`` ({alias: current official symbol}). Offline,
# ~370 KB, regenerated by scripts/generate_ncbi_symbol_synonyms.py. It
# is the last resort in symbol resolution — consulted only when a name
# matches no installed Ensembl release and is not a curated display
# alias (e.g. GNB2L1→RACK1, TCEB2→ELOB, NARS→NARS1).
# ---------------------------------------------------------------------------

_NCBI_SYNONYMS_PATH = Path(__file__).parent / "data" / "ncbi-symbol-synonyms.csv.gz"


@lru_cache(maxsize=1)
def _ncbi_symbol_synonyms() -> dict:
    """Load the bundled {alias: official_symbol} snapshot (offline).

    Only unambiguous, guard-checked aliases are present (see the
    generator). A missing file degrades gracefully to an empty map, so
    the lowest tier simply yields nothing rather than erroring.
    """
    out: dict[str, str] = {}
    try:
        with gzip.open(
            _NCBI_SYNONYMS_PATH, "rt", encoding="utf-8", newline="",
        ) as f:
            reader = csv.reader(f)
            next(reader, None)  # header
            for row in reader:
                if len(row) >= 2 and row[0] and row[1]:
                    out[row[0]] = row[1]
    except FileNotFoundError:
        pass
    return out


def ncbi_synonym_official_symbol(name: str) -> Optional[str]:
    """Map a legacy/alternate symbol to its current official symbol, or None.

    Tries the name as given then upper-cased (most legacy symbols are
    upper-case, e.g. ``gnb2l1`` → ``GNB2L1`` → ``RACK1``). Backed by the
    bundled NCBI synonym snapshot; never reassigns a live official symbol
    (those are excluded at generation time).
    """
    table = _ncbi_symbol_synonyms()
    s = str(name).strip()
    return table.get(s) or table.get(s.upper())


def _index_cache_path(release: int):
    """Cache location for the prebuilt Ensembl id→name dicts.

    Honors ``XDG_CACHE_HOME`` (Linux convention) and falls back to
    ``~/.cache/pirlygenes/``. Returns a Path; the directory is created
    lazily by the writer.
    """
    import os as _os
    from pathlib import Path as _Path
    base = _os.environ.get("XDG_CACHE_HOME") or str(_Path.home() / ".cache")
    return _Path(base) / "pirlygenes" / f"ensembl-{release}-id-index.pkl"


# Minimum expected dictionary size. A real human Ensembl release has
# ~20k–80k genes and ~200k–400k transcripts. Anything below this
# threshold is presumed to be a test-fixture or partial-build cache
# (e.g. a fake-genome unit test that accidentally wrote into the real
# user cache) and is treated as corrupt — the cache is rebuilt from
# pyensembl. Fixed in 5.4.1 after such a 1-entry fixture cache was
# found in a developer's home cache during release prep.
_MIN_SANE_GENE_COUNT = 1000
_MIN_SANE_TRANSCRIPT_COUNT = 5000


def _load_index_cache(release: int):
    """Return (gene_dict, transcript_dict) from the pickle cache, or None.

    Each subprocess pays ~2s to walk pyensembl's gene/transcript tables
    when first resolving Ensembl IDs. Loading the prebuilt dicts from
    a single ~5MB pickle is sub-300ms and is shared across the OS page
    cache when many processes mmap the same file."""
    import pickle as _pickle
    path = _index_cache_path(release)
    if not path.exists():
        return None
    try:
        with path.open("rb") as f:
            payload = _pickle.load(f)
        if not isinstance(payload, dict):
            return None
        if payload.get("release") != release:
            return None
        gene_map = payload["gene_id_to_name"]
        transcript_map = payload["transcript_id_to_gene_name"]
        if (
            len(gene_map) < _MIN_SANE_GENE_COUNT
            or len(transcript_map) < _MIN_SANE_TRANSCRIPT_COUNT
        ):
            # Suspiciously tiny — treat as corrupt + rebuild.
            return None
        return gene_map, transcript_map
    except Exception:
        return None


def _store_index_cache(release: int, gene_map: dict, transcript_map: dict) -> None:
    import pickle as _pickle
    path = _index_cache_path(release)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        with tmp.open("wb") as f:
            _pickle.dump(
                {
                    "release": release,
                    "gene_id_to_name": gene_map,
                    "transcript_id_to_gene_name": transcript_map,
                },
                f,
                protocol=_pickle.HIGHEST_PROTOCOL,
            )
        tmp.replace(path)
    except Exception:
        if tmp.exists():
            tmp.unlink(missing_ok=True)


def _build_indexes():
    global _gene_id_to_name, _transcript_id_to_gene_name, _indexes_built
    if _indexes_built:
        return
    if not genomes:
        _indexes_built = True
        return
    g = genomes[0]
    cached = _load_index_cache(g.release)
    if cached is not None:
        _gene_id_to_name, _transcript_id_to_gene_name = cached
        print(
            f"[index] Loaded {len(_gene_id_to_name)} genes, "
            f"{len(_transcript_id_to_gene_name)} transcripts from cache "
            f"(release {g.release})"
        )
        _indexes_built = True
        return
    print(f"[index] Building gene/transcript index from Ensembl release {g.release}...")
    try:
        for gene in g.genes():
            _gene_id_to_name[strip_version(gene.id)] = gene.name
    except Exception:
        pass
    try:
        for t in g.transcripts():
            _transcript_id_to_gene_name[strip_version(t.id)] = t.gene_name
    except Exception:
        pass
    print(
        f"[index] {len(_gene_id_to_name)} genes, {len(_transcript_id_to_gene_name)} transcripts indexed"
    )
    _store_index_cache(g.release, _gene_id_to_name, _transcript_id_to_gene_name)
    _indexes_built = True


def _lookup_gene_name_in_older_releases(gene_id: str) -> Optional[str]:
    """Resolve a gene ID against older installed releases on demand.

    The fast path indexes only the newest release. When a sample was
    quantified against an older annotation, valid IDs can disappear from
    that latest-only map; we need a correctness-preserving fallback
    instead of silently treating them as unresolved.
    """
    gid = strip_version(gene_id)
    if gid in _gene_id_miss_cache:
        return None
    for genome in genomes[1:]:
        gene = gene_for_ensembl_id(genome, gid)
        if gene and gene.gene_name:
            _gene_id_to_name[gid] = gene.gene_name
            return gene.gene_name
    _gene_id_miss_cache.add(gid)
    return None


def _lookup_transcript_name_in_older_releases(t_id: str) -> Optional[str]:
    """Resolve a transcript ID against older installed releases on demand."""
    tid = strip_version(t_id)
    if tid in _transcript_id_miss_cache:
        return None
    for genome in genomes[1:]:
        try:
            transcript = genome.transcript_by_id(tid)
        except Exception:
            transcript = None
        if transcript and transcript.gene_name:
            _transcript_id_to_gene_name[tid] = transcript.gene_name
            return transcript.gene_name
    _transcript_id_miss_cache.add(tid)
    return None


def find_gene_name_from_ensembl_gene_id(
    gene_id: str, verbose: bool = False
) -> Optional[str]:
    _build_indexes()
    gid = strip_version(gene_id)
    name = _gene_id_to_name.get(gid)
    if name is None:
        name = _lookup_gene_name_in_older_releases(gid)
    if name and verbose:
        print("Found %s -> %s" % (gene_id, name))
    return name


def find_gene_name_from_ensembl_transcript_id(
    t_id: str, verbose: bool = False
) -> Optional[str]:
    _build_indexes()
    tid = strip_version(t_id)
    name = _transcript_id_to_gene_name.get(tid)
    if name is None:
        name = _lookup_transcript_name_in_older_releases(tid)
    if name and verbose:
        print("Found %s -> %s" % (t_id, name))
    return name


def _best_canonical_cds_length(gene) -> int:
    """Longest CDS length (nt) among the gene's protein-coding transcripts — a
    proxy for 'longer CDS on the canonical transcript' (pyensembl doesn't flag
    canonical, and the canonical is ~always the longest complete CDS)."""
    best = 0
    for t in gene.transcripts:
        if not t.is_protein_coding:
            continue
        try:
            cds = t.coding_sequence
            if cds:
                best = max(best, len(cds))
        except Exception:
            continue
    return best


def _best_transcript_support(gene) -> int:
    """Quality of the gene's best transcript as a sortable score (higher is
    better). Ensembl TSL is 1 (best) .. 5 (worst); we invert to -min(TSL), and
    fall back to 0 when no TSL is annotated."""
    levels = []
    for t in gene.transcripts:
        sl = getattr(t, "support_level", None)
        try:
            levels.append(int(sl))
        except (TypeError, ValueError):
            continue
    return -min(levels) if levels else 0


def pick_best_gene(genes):
    """Choose one gene when a symbol maps to several. Preference order
    (most→least important): (1) a protein-coding gene over a non-coding one;
    (2) higher-quality best transcript (lowest Ensembl TSL); (3) longer CDS on
    the canonical (longest-CDS) transcript; (4) more coding transcripts; then a
    stable name tie-break. Symbols resolve to ONE Ensembl gene id; that id is
    the only key used for joins/comparisons downstream."""
    if len(genes) == 0:
        raise ValueError("Expected at least one gene, got none")
    if len(genes) == 1:
        return genes[0]  # fast path: no collision, skip the (costly) CDS probe

    def sort_key(g):
        coding = 1 if getattr(g, "biotype", "") == "protein_coding" else 0
        num_protein_coding = sum(t.is_protein_coding for t in g.transcripts)
        return (
            coding,                          # (1) prefer the coding gene
            _best_transcript_support(g),     # (2) higher-quality transcript
            _best_canonical_cds_length(g),   # (3) longer canonical CDS
            num_protein_coding,              # (4) more coding transcripts
            -g.name.count("."),
            len(g.name),
            g.name,
        )

    return sorted(genes, key=sort_key, reverse=True)[0]


def find_gene_and_ensembl_release_by_name(
    name: str,
    verbose: bool = False,
) -> Optional[Tuple[pyensembl.Genome, pyensembl.Gene]]:
    for genome in genomes:
        candidates = set(
            [name, short_gene_name(name)]
            + get_alias_as_list(name)
            + get_reverse_alias_as_list(name)
        )
        for n in list(candidates):
            candidates.add(n.lower())
            candidates.add(n.upper())

        for n in candidates:
            if verbose:
                print("--> %s: %s" % (genome, n))
            try:
                genes = genome.genes_by_name(n)
            except Exception:
                genes = []
            if len(genes) >= 1:
                return genome, pick_best_gene(genes)

    # Lowest tier — if all else fails: a legacy/alternate symbol that no
    # installed release knows and that isn't a curated display alias.
    # Map it to its current official symbol via the bundled NCBI synonym
    # snapshot, then resolve that the normal way.
    official = ncbi_synonym_official_symbol(name)
    if official and official != name:
        for genome in genomes:
            try:
                genes = genome.genes_by_name(official)
            except Exception:
                genes = []
            if len(genes) >= 1:
                if verbose:
                    print("--> ncbi-synonym %s -> %s (%s)" % (name, official, genome))
                return genome, pick_best_gene(genes)


def find_gene_by_name_from_ensembl(
    name: str, verbose: bool = False
) -> Optional[pyensembl.Gene]:
    result = find_gene_and_ensembl_release_by_name(name, verbose=verbose)
    if result is not None:
        _, gene = result
        return gene


def find_gene_id_by_name_from_ensembl(
    name: str, verbose: bool = False
) -> Optional[str]:
    gene = find_gene_by_name_from_ensembl(name, verbose=verbose)
    if gene is not None:
        return gene.id


def find_canonical_gene_id_and_name(
    gene_name: str,
) -> Tuple[Optional[str], Optional[str]]:
    gene = find_gene_by_name_from_ensembl(gene_name)
    if gene:
        return gene.id, gene.name
    else:
        return None, None


def find_canonical_gene_ids_and_names(
    gene_names: Sequence[str],
    verbose: bool = False,
) -> Tuple[List[Optional[str]], List[Optional[str]]]:
    gene_ids = []
    canonical_gene_names = []

    for gene_name in tqdm(
        gene_names, "Finding canonical gene IDs and names", disable=not verbose
    ):
        gene_id, canonical_name = find_canonical_gene_id_and_name(gene_name)
        if verbose:
            print(
                "Found %s -> %s" % (gene_name, gene_id or "None")
                if gene_id
                else "Not found: %s" % gene_name
            )
        gene_ids.append(gene_id)
        canonical_gene_names.append(canonical_name)
    return gene_ids, canonical_gene_names
