"""Curated QC feature groups keyed by Ensembl Gene ID.

These CSVs are generated by ``scripts/generate_qc_gene_sets.py`` by
walking every installed GRCh38 Ensembl release and applying the
symbol-level regex from
:func:`trufflepig.expression_qc.classify_gene_qc`.

Use the typed accessors here instead of re-implementing the regex —
ENSG lookup is stable across HGNC symbol renames (MLL→KMT2A,
MARCH1→MARCHF1, etc.) and survives cross-source joins (TCGA × HPA ×
Treehouse) without alias resolution.

Row schema:

    Ensembl_Gene_ID       — unversioned (ENSG00000251562)
    Symbol                — HGNC symbol (uppercase)
    qc_group              — coarse category (see classify_gene_qc)
    qc_label              — human-readable label
    ensembl_releases      — ;-joined list of releases that matched
    biotypes              — ;-joined list of biotypes seen
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import pandas as pd


_DATA_DIR = Path(__file__).resolve().parent / "data"

# Ordered so that the more specific group wins if a gene happens to
# appear in multiple files (shouldn't happen, but defensive).
QC_FEATURE_FILES: tuple[tuple[str, str], ...] = (
    ("mt_dna", "qc-mt-dna.csv"),
    ("mt_like_pseudogene", "qc-mt-like-pseudogene.csv"),
    ("polyadenylation_bias_lncrna", "qc-polya-bias-lncrna.csv"),
    ("rrna_like", "qc-rrna-like.csv"),
    ("ribosomal_protein_pseudogene", "qc-ribosomal-protein-pseudogene.csv"),
    ("ribosomal_protein", "qc-ribosomal-protein.csv"),
    ("small_ncrna", "qc-small-ncrna.csv"),
    ("histone", "qc-histone.csv"),
    ("hemoglobin", "qc-hemoglobin.csv"),
    ("immune_receptor", "qc-immune-receptor.csv"),
)


@dataclass(frozen=True)
class QcFeatureClass:
    """Resolved QC category for a feature."""

    ensembl_gene_id: str
    symbol: str
    group: str
    label: str


def _strip_version(ensg: str) -> str:
    """``ENSG00000251562.5`` → ``ENSG00000251562``."""
    return str(ensg or "").split(".", 1)[0].strip()


@lru_cache(maxsize=1)
def _load_table() -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for qc_group, fname in QC_FEATURE_FILES:
        path = _DATA_DIR / fname
        if not path.is_file():
            continue
        df = pd.read_csv(path)
        if "qc_group" not in df.columns:
            df["qc_group"] = qc_group
        frames.append(df)
    if not frames:
        return pd.DataFrame(
            columns=[
                "Ensembl_Gene_ID",
                "Symbol",
                "qc_group",
                "qc_label",
                "ensembl_releases",
                "biotypes",
            ]
        )
    out = pd.concat(frames, ignore_index=True, sort=False)
    out["Ensembl_Gene_ID"] = out["Ensembl_Gene_ID"].astype(str).map(_strip_version)
    out["Symbol"] = out["Symbol"].astype(str).str.upper().str.strip()
    return out


def qc_feature_table() -> pd.DataFrame:
    """Long-form QC classification table across all groups (one row per ENSG×group)."""
    return _load_table().copy()


@lru_cache(maxsize=1)
def _by_ensembl() -> dict[str, QcFeatureClass]:
    df = _load_table()
    out: dict[str, QcFeatureClass] = {}
    # Iterate in the curated group order so the first match wins for
    # IDs that somehow appear in multiple groups (defensive).
    group_order = {g: i for i, (g, _) in enumerate(QC_FEATURE_FILES)}
    df = df.assign(_order=df["qc_group"].map(group_order).fillna(len(group_order)))
    for _, row in df.sort_values("_order").iterrows():
        ensg = row["Ensembl_Gene_ID"]
        if ensg in out:
            continue
        out[ensg] = QcFeatureClass(
            ensembl_gene_id=ensg,
            symbol=row["Symbol"],
            group=row["qc_group"],
            label=row.get("qc_label", ""),
        )
    return out


@lru_cache(maxsize=1)
def _by_symbol() -> dict[str, QcFeatureClass]:
    df = _load_table()
    out: dict[str, QcFeatureClass] = {}
    group_order = {g: i for i, (g, _) in enumerate(QC_FEATURE_FILES)}
    df = df.assign(_order=df["qc_group"].map(group_order).fillna(len(group_order)))
    for _, row in df.sort_values("_order").iterrows():
        sym = str(row["Symbol"]).strip().upper()
        if sym in out:
            continue
        out[sym] = QcFeatureClass(
            ensembl_gene_id=row["Ensembl_Gene_ID"],
            symbol=sym,
            group=row["qc_group"],
            label=row.get("qc_label", ""),
        )
    return out


def qc_class_for_ensembl_id(ensembl_id: str | None) -> QcFeatureClass | None:
    """ENSG → QcFeatureClass; ``None`` if the ID isn't in any group."""
    if not ensembl_id:
        return None
    return _by_ensembl().get(_strip_version(ensembl_id))


def qc_class_for_symbol(symbol: str | None) -> QcFeatureClass | None:
    """Symbol → QcFeatureClass; ``None`` if the symbol isn't in any group.

    For runtime classification prefer
    :func:`trufflepig.expression_qc.classify_gene_qc` — it falls back
    to the source-of-truth regex for unmapped symbols.
    """
    if not symbol:
        return None
    return _by_symbol().get(str(symbol).strip().upper())


def qc_feature_groups() -> dict[str, pd.DataFrame]:
    """Return ``{group_name: DataFrame}`` for every QC group on disk."""
    df = _load_table()
    out: dict[str, pd.DataFrame] = {}
    for group_name, _ in QC_FEATURE_FILES:
        sub = df[df["qc_group"] == group_name].copy()
        if not sub.empty:
            out[group_name] = sub.reset_index(drop=True)
    return out


def qc_feature_ensembl_ids(group: str) -> set[str]:
    """Set of unversioned ENSG IDs for one QC group."""
    df = _load_table()
    return set(df.loc[df["qc_group"] == group, "Ensembl_Gene_ID"].astype(str))


def qc_feature_symbols(group: str) -> set[str]:
    """Set of uppercase symbols for one QC group."""
    df = _load_table()
    return set(df.loc[df["qc_group"] == group, "Symbol"].astype(str).str.upper())


__all__ = [
    "QcFeatureClass",
    "qc_feature_table",
    "qc_feature_groups",
    "qc_feature_ensembl_ids",
    "qc_feature_symbols",
    "qc_class_for_ensembl_id",
    "qc_class_for_symbol",
]
