"""Refresh the pinned NCBI gene-data mirror the builders load from.

At build time, ``pirlygenes.builders.ncbi_gene_info`` fetches
``Homo_sapiens.gene_info.gz`` + ``gene_history.gz`` from a pinned GitHub
release (``GENE_DATA_MIRROR_TAG``), not from NCBI — so builds are
reproducible and don't depend on NCBI's FTP. When NCBI publishes fresher
data, refresh the mirror:

    python scripts/refresh_ncbi_gene_data.py --tag ncbi-gene-data-YYYYMMDD

This pulls both files from NCBI upstream into a temp dir and uploads them
to a NEW GitHub release under ``<tag>``. Afterwards:

  1. Bump ``GENE_DATA_MIRROR_TAG`` in
     ``pirlygenes/builders/ncbi_gene_info.py`` to the new tag.
  2. Drop the stale local cache and regenerate the synonym snapshot:
       rm ~/.cache/pirlygenes/ncbi_gene_info/Homo_sapiens.gene_info.gz
       python scripts/generate_ncbi_symbol_synonyms.py

Pass ``--no-upload`` to only download (e.g. to inspect), or ``--target``
to point the release tag at a specific git ref (default: ``main``).
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import tempfile
import urllib.request
from pathlib import Path

from pirlygenes.builders.ncbi_gene_info import (
    NCBI_GENE_HISTORY_UPSTREAM_URL,
    NCBI_GENE_INFO_UPSTREAM_URL,
)

UPSTREAM_FILES = {
    "Homo_sapiens.gene_info.gz": NCBI_GENE_INFO_UPSTREAM_URL,
    "gene_history.gz": NCBI_GENE_HISTORY_UPSTREAM_URL,
}


def _download(url: str, dest: Path) -> None:
    print(f"  downloading {url}")
    with urllib.request.urlopen(url) as resp, dest.open("wb") as handle:
        shutil.copyfileobj(resp, handle, length=1024 * 1024)
    print(f"    -> {dest.name} ({dest.stat().st_size / 1e6:.0f} MB)")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _gh_tag_exists(tag: str) -> bool:
    return subprocess.run(
        ["gh", "release", "view", tag],
        capture_output=True, text=True,
    ).returncode == 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Refresh the pinned NCBI gene-data GitHub mirror.",
    )
    parser.add_argument(
        "--tag", required=True,
        help="new release tag, e.g. ncbi-gene-data-20260601",
    )
    parser.add_argument(
        "--target", default="main",
        help="git ref the release tag points at (default: main)",
    )
    parser.add_argument(
        "--no-upload", action="store_true",
        help="download from NCBI only; skip the gh release upload",
    )
    args = parser.parse_args()

    # Fail fast — before the ~165 MB download — if the tag is already taken
    # (gh release create would otherwise error only after the upload).
    if not args.no_upload and _gh_tag_exists(args.tag):
        parser.error(f"release {args.tag!r} already exists — pick a new dated tag")

    tmp = Path(tempfile.mkdtemp(prefix="ncbi-gene-data-"))
    try:
        paths = []
        for name, url in UPSTREAM_FILES.items():
            dest = tmp / name
            _download(url, dest)
            paths.append(dest)

        # Report digests so they can go in the release notes / be audited.
        for p in paths:
            print(f"  sha256 {p.name}: {_sha256(p)}")

        if args.no_upload:
            print(f"downloaded to {tmp} (upload skipped — clean up manually)")
            return

        cmd = [
            "gh", "release", "create", args.tag,
            "--target", args.target,
            "--title", f"NCBI gene-data mirror — {args.tag}",
            "--notes", (
                "Pinned mirror of Homo_sapiens.gene_info.gz + gene_history.gz "
                "from NCBI, consumed by pirlygenes.builders.ncbi_gene_info. "
                "Generated by scripts/refresh_ncbi_gene_data.py."
            ),
            *(str(p) for p in paths),
        ]
        print("running:", " ".join(cmd))
        subprocess.run(cmd, check=True)
        print(
            f"\nuploaded. Next: set GENE_DATA_MIRROR_TAG = '{args.tag}' in "
            "pirlygenes/builders/ncbi_gene_info.py, then regenerate the synonym "
            "snapshot (scripts/generate_ncbi_symbol_synonyms.py)."
        )
    finally:
        # Keep the temp dir only when the user asked to inspect it.
        if not args.no_upload:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
