name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install pytest pytest-cov coveralls pylint ruff
          uv pip install .
      - name: Cache pyensembl data
        uses: actions/cache@v4
        with:
          path: ~/.cache/pyensembl/
          key: pyensembl-112-${{ runner.os }}
      - name: Install Ensembl genome data
        run: |
          source .venv/bin/activate
          echo "Before installing Ensembl release 112" && df -h
          pyensembl install --release 112 --species homo_sapiens
          echo "After installing Ensembl release 112" && df -h
      - name: Run linting script and unit tests
        run: |
          source .venv/bin/activate
          ./lint.sh
          ./test.sh
